### ISSUE TITLE
Kleines statt großem S in Abhängigkeit

### ISSUE THREAD

**Issue by caha42** [DLR-SC/DataFinder#3]
datafinder/build_scripts/distutils/src/datafinder_distutils/targets/bdist.py 
Statt datafinder.persistence.adapters.amazons3.factory muss da datafinder.persistence.adapters.amazonS3.factory hin. Das s ist groß geworden, warum oder wie auch immer.

**Comment by schlauch** [comment]
This causes some additional errors. Some unit tests concerning amzonS3 fail.

**Comment by schlauch** [comment]
Seems to be the result of an incomplete refactoring. Fixed it.
